raise Exception('This is the error message.')